### ISSUE TITLE
where can i find these templates if i want to contribute

### ISSUE THREAD

**Issue by TobyGE** [chujiezheng/chat_templates#1]

**Comment by chujiezheng** [comment]
Hi, thanks for your interest!

Currently, I collected these templates manually, based on my scanning over HuggingFace model cards and leaderboards (e.g., the Chatbot Arena).

1. I would check their `README` files (for usage examples) and their `tokenizer_config.json` files.
2. For those that specifically indicate the input format but do not include in the `tokenizer_config.json` file, I would create the corresponding `jinja` file in this repo.
