### ISSUE TITLE
ChatQA empty

### ISSUE THREAD

**Issue by Luke100000** [chujiezheng/chat_templates#25]
I believe [`chatqa.jinja`](https://github.com/chujiezheng/chat_templates/blob/main/chat_templates/chatqa.jinja) is not working as intended, `content` is not set.
Can it be `message['content']` or is further processing required?

E.g.,
```jinja
    {% if message['role'] == 'user' %}
        {{ '\n\nUser: ' + message['content'] | trim }}
    {% elif message['role'] == 'assistant' %}
        {{ '\n\nAssistant: '  + message['content'] | trim }}
    {% endif %}
```

**Comment by chujiezheng** [comment]
Thanks for your reminder. I have fixed it.
