### ISSUE TITLE
Saiga syntax error

### ISSUE THREAD

**Issue by Luke100000** [chujiezheng/chat_templates#26]
The sets in [saiga](https://github.com/chujiezheng/chat_templates/blob/main/chat_templates/saiga.jinja) do not compile for me, rewriting them like these works:

```jinja
    {% if message['role'] == 'assistant' %}
        {% set role = 'bot' %}
    {% else %}
        {% set role = message['role'] %}
    {% endif %}
```

Thanks for this repo :)

**Comment by chujiezheng** [comment]
Thanks for your reminder. I have fixed it.
